packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@mongodb-js/zstd': false
  '@swc/core': false
  better-sqlite3: true
  cbor-extract: false
  esbuild: true
  node-liblzma: false
  sharp: true
minimumReleaseAgeExclude:
  - hono@4.12.31
  - '@radix-ui/primitive@1.1.6'
  - '@radix-ui/react-arrow@1.1.12'
  - '@radix-ui/react-dialog@1.1.20'
  - '@radix-ui/react-dismissable-layer@1.1.16'
  - '@radix-ui/react-focus-scope@1.1.13'
  - '@radix-ui/react-popover@1.1.20'
  - '@radix-ui/react-popper@1.3.4'
  - '@radix-ui/react-portal@1.1.14'
  - '@radix-ui/react-presence@1.1.8'
  - '@radix-ui/react-roving-focus@1.1.16'
  - '@radix-ui/react-scroll-area@1.2.15'
  - '@radix-ui/react-select@2.3.4'
  - '@radix-ui/react-tabs@1.1.18'
  - '@radix-ui/react-tooltip@1.2.13'
  - '@radix-ui/react-use-controllable-state@1.2.4'
  - '@radix-ui/react-visually-hidden@1.2.8'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
