import { addPaper, ensureIndexes, searchPapers } from '../packages/helix/src/index.ts'

const SEED_PAPERS = [
  {
    title: 'Nanoflare heating of the solar corona via magnetic reconnection',
    abstract:
      'Parker proposed that the solar corona is heated by nanoflares — tiny magnetic reconnection events releasing ~10^24 erg each. The cumulative effect of millions of nanoflares can sustain coronal temperatures at 1-3 MK. Observational signatures include non-thermal line broadening in EUV spectra and intermittent brightenings in active region loops.',
    authors: ['Parker EN'],
    year: 1988,
    doi: '10.1086/166285',
  },
  {
    title: 'Alfvén wave dissipation and coronal heating in open magnetic flux tubes',
    abstract:
      'Alfvén waves generated by photospheric granular motions propagate along open magnetic flux tubes and dissipate via ion cyclotron resonance in the low corona. The wave energy flux of ~300 W/m² is sufficient to heat the quiet Sun corona. SDO/AIA observations show wave signatures in 171Å and 335Å channels.',
    authors: ['Cranmer SR', 'van Ballegooijen AA'],
    year: 2010,
    doi: '10.1088/0004-637X/720/1/494',
  },
  {
    title: 'Turbulent cascade and kinetic scale dissipation in the solar corona',
    abstract:
      'MHD turbulence driven by photospheric footpoint motions cascades energy from large-scale Alfvén waves to kinetic scales where collisionless Landau damping dissipates energy into electrons and ions. Power-law intensity fluctuations with spectral slopes steeper than -1.8 in SDO/AIA time series provide observational evidence.',
    authors: ['Howes GG', 'Bale SD'],
    year: 2012,
    doi: '10.1088/0004-637X/753/1/19',
  },
  {
    title: 'Magnetic carpet reconnection and coronal heating: SOHO observations',
    abstract:
      'The magnetic carpet — small-scale magnetic flux elements on the solar surface — drives reconnection events that heat the corona. SOHO/MDI magnetograms show that flux cancellation rates are sufficient to supply the 300 W/m² needed for quiet Sun heating. EUV brightenings correlate with magnetic flux emergence events.',
    authors: ['Close RM', 'Parnell CE', 'Priest ER'],
    year: 2004,
    doi: '10.1051/0004-6361:20035850',
  },
  {
    title: 'Coronal heating by DC electric currents and magnetic stress',
    abstract:
      'DC electric currents induced by photospheric footpoint motions build up magnetic stress in coronal loops. When stress exceeds a critical threshold, reconnection releases stored energy. This mechanism predicts heating concentrated at loop tops and along separators. Hinode/XRT observations show hot plasma at loop apexes consistent with DC heating.',
    authors: ['Klimchuk JA'],
    year: 2006,
    doi: '10.1088/0031-8949/74/1/003',
  },
  {
    title: 'Wave heating versus nanoflare heating: a unified model',
    abstract:
      'A combined AC+DC model where Alfvén waves and nanoflares contribute at different heights: wave heating dominates in open field regions and the upper corona, while nanoflare reconnection dominates in closed loops and the lower corona. IRIS observations of Si IV line widths support this dual-mechanism picture.',
    authors: ['Aschwanden MJ', 'Peter H'],
    year: 2017,
    doi: '10.1088/0004-637X/836/1/11',
  },
  {
    title: 'Optimal nanoflare energy distribution from Hinode/EIS observations',
    abstract:
      'Hinode/EIS spectroscopic observations of active region loops constrain the nanoflare energy distribution. The observed non-thermal velocity distribution (10-30 km/s) and differential emission measure are consistent with a power-law nanoflare energy spectrum with index -1.5. This supports the Parker nanoflare model over wave heating in closed loops.',
    authors: ['Brooks DH', 'Warren HP'],
    year: 2016,
    doi: '10.1088/0004-637X/820/1/63',
  },
  {
    title: 'Alfvén wave energy flux measurements from Solar Orbiter',
    abstract:
      'Solar Orbiter in-situ measurements of magnetic field fluctuations at 0.5 AU confirm Alfvénic wave energy fluxes of 500-1000 W/m², more than sufficient for coronal heating. The wave spectrum shows a Kolmogorov -5/3 power law consistent with turbulent dissipation. This strongly supports AC wave heating models for the extended corona.',
    authors: ['Bale SD', 'Stverak SV'],
    year: 2021,
    doi: '10.1038/s41550-021-01318-9',
  },
  {
    title: 'IRIS observations of nanoflare signatures in the transition region',
    abstract:
      'IRIS slit-jaw images in Si IV 1400Å reveal intermittent brightenings at the footpoints of coronal loops, consistent with nanoflare energy release. Non-thermal line broadening exceeds 50 km/s during these events. The observed energy release rate matches Parker model predictions for active region heating.',
    authors: ['Testa P', 'De Pontieu B'],
    year: 2014,
    doi: '10.1126/science.1255723',
  },
  {
    title: 'MHD simulation of turbulent coronal heating with realistic photospheric driving',
    abstract:
      '3D MHD simulations with realistic photospheric boundary conditions show that turbulent dissipation of footpoint-driven Alfvén waves heats the corona to 1-2 MK. The simulated temperature and density profiles match SDO/AIA observations. Dissipation occurs primarily at current sheets formed by magnetic braiding.',
    authors: ['Rappazzo AF', 'Velli M'],
    year: 2015,
    doi: '10.1088/0004-637X/799/2/145',
  },
]

async function main() {
  console.log('Ensuring indexes...')
  await ensureIndexes()

  console.log(`Seeding ${SEED_PAPERS.length} papers...`)
  for (const paper of SEED_PAPERS) {
    await addPaper({
      title: paper.title,
      abstract: paper.abstract,
      authors: paper.authors,
      year: paper.year,
      doi: paper.doi,
    })
    console.log(`  ✓ ${paper.title.slice(0, 60)}...`)
  }

  console.log('\nVerifying: searching for "nanoflare coronal heating"...')
  const results = await searchPapers('nanoflare coronal heating', 5)
  console.log(`  Found ${results.length} papers:`)
  for (const p of results) {
    console.log(`    - [${p.year}] ${p.title}`)
  }

  console.log('\nDone!')
}

main().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
